<?php
header('Content-type: text/json');
?>
{
    "success": true,
    "code": 200,
    "msg": "操作成功",
    "obj": null,
    "map": {
        "count": 7,
        "pageNo": 1,
        "pageSize": 12
    },
    "list": [
        {
            "id": 2248642,
            "name": "888",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1426056100000,
            "type": 1,
            "pageMode": 2,
            "image": {
                "imgSrc": "group1/M00/A2/F4/yq0KA1Qb5EyAT31mAADGlhZbl7k638.jpg",
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1426056100000,
            "publishTime": null,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": null,
            "code": "bIciYk",
            "description": null,
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 0,
            "userLoginName": null,
            "userName": null
        },
        {
            "id": 2227077,
            "name": "test123",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1425998747000,
            "type": 1,
            "pageMode": 2,
            "image": {
                "imgSrc": "group1/M00/A2/F4/yq0KA1Qb5EyAT31mAADGlhZbl7k638.jpg",
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1426053542000,
            "publishTime": 1426053542000,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": null,
            "code": "FuDCYt",
            "description": null,
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 15,
            "userLoginName": null,
            "userName": null
        },
        {
            "id": 2225156,
            "name": "test",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1425995567000,
            "type": 1,
            "pageMode": 2,
            "image": {
                "imgSrc": "group1/M00/A2/F4/yq0KA1Qb5EyAT31mAADGlhZbl7k638.jpg",
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1425995895000,
            "publishTime": 1425995895000,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": null,
            "code": "Az8SLr",
            "description": null,
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 0,
            "userLoginName": null,
            "userName": null
        },
        {
            "id": 2216690,
            "name": "两会报告",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1425981055000,
            "type": 5,
            "pageMode": 2,
            "image": {
                "imgSrc": "group1/M00/1B/99/yq0KA1TPU2WATyVAAAB-gYCOSzw904.jpg",
                "hideEqAd": false,
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1425981055000,
            "publishTime": null,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": 916379,
            "code": "47LUnc",
            "description": null,
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 3,
            "userLoginName": null,
            "userName": null
        },
        {
            "id": 1290387,
            "name": "印通天下",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1423646055000,
            "type": 1,
            "pageMode": 0,
            "image": {
                "imgSrc": "group1/M00/A2/F4/yq0KA1Qb5EyAT31mAADGlhZbl7k638.jpg",
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1423646315000,
            "publishTime": 1423646306000,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": null,
            "code": "moVU2S",
            "description": null,
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 5,
            "userLoginName": null,
            "userName": null
        },
        {
            "id": 1289544,
            "name": "印通天下",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1423645237000,
            "type": 8,
            "pageMode": 0,
            "image": {
                "bgAudio": {
                    "url": "group1/M00/B7/4F/yq0KA1RHT4CAGCJkAAraxfiUnJQ192.mp3",
                    "type": "3"
                },
                "imgSrc": "group1/M00/8A/DA/yq0KA1TZgEWAYnuCAAE7RT7VCAI735.jpg",
                "hideEqAd": false,
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1423645519000,
            "publishTime": 1423645519000,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": 1225273,
            "code": "SSnMxk",
            "description": "印通天下测试",
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 4,
            "userLoginName": null,
            "userName": null
        },
        {
            "id": 1289517,
            "name": "App一秀使用手册",
            "createUser": "4a2d8aae4b7282aa014b77de0b55210b",
            "createTime": 1423645215000,
            "type": 1,
            "pageMode": 1,
            "image": {
                "imgSrc": "group1/M00/D7/A9/yq0KA1SSwtuANy0oAAAnqVulopQ252.jpg",
                "hideEqAd": false,
                "isAdvancedUser": false
            },
            "isTpl": 0,
            "isPromotion": 0,
            "status": 1,
            "openLimit": 0,
            "submitLimit": 0,
            "startDate": null,
            "endDate": null,
            "accessCode": null,
            "thirdCode": null,
            "updateTime": 1423645215000,
            "publishTime": null,
            "applyTemplate": 0,
            "applyPromotion": 0,
            "sourceId": 10261,
            "code": "5Ct6a8",
            "description": null,
            "sort": 0,
            "pageCount": 0,
            "dataCount": 0,
            "showCount": 0,
            "userLoginName": null,
            "userName": null
        }
    ]
}